[features]
seeds = false
skip-lint = false
[programs.mainnet]
upgrade = "67714KFVqCYNTu7NUCjtMuid55dKutnXmjXpeqJEwmpu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Mainnet"
wallet = "/Users/coach/.config/solana/projects/clicker.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 3000

[test.validator]
url="https://api.mainnet-beta.solana.com"

[[test.validator.clone]] # Metaplex
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

[[test.validator.clone]] # ATA
address = "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"

[[test.validator.clone]] # Token
address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"